function zad18(r::Robot)
    North = HorizonSide(0)
    South = HorizonSide(2)
    West = HorizonSide(1)
    East = HorizonSide(3)
    backpath = go_to_some_corner_and_return_path!(r, North, West, go_around_barriers=true)
    putmarker!(r)
    go_by_path!(r, backpath)
    backpath = go_to_some_corner_and_return_path!(r, South, West, go_around_barriers=true)
    putmarker!(r)
    go_by_path!(r, backpath)
    backpath = go_to_some_corner_and_return_path!(r, South, East, go_around_barriers=true)
    putmarker!(r)
    go_by_path!(r, backpath)
    backpath = go_to_some_corner_and_return_path!(r, North, East, go_around_barriers=true)
    putmarker!(r)
    go_by_path!(r, backpath)
end